### ISSUE TITLE
Include EFS icon

### ISSUE THREAD

**Issue by runningman84** [abesto/yed-aws-palettes#2]
Please add the latest aws icons.

**Comment by abesto** [comment]
Thanks for asking!

I've imported the latest version in https://github.com/abesto/yed-aws-palettes/commit/d9069572a7ca464b79e4062a83882b1ae5df59f3. Unfortunately the icon set distributed by AWS at https://aws.amazon.com/architecture/icons/ (SVG and EFS Format) doesn't contain icons for a bunch of services, apparently nothing in preview; that includes EFS and Lambda, for example.

Closing for now since there's not much we can do until Amazon releases new icons. Please feel free to open a new issue when there are new icons in the pack.
